# Prover configuration for noir-symmetric-crypto
# This file contains input parameters for proving symmetric cryptography circuits

# ChaCha20 test vectors
[chacha20]
# 256-bit key (32 bytes)
key = [
    "0x00", "0x01", "0x02", "0x03", "0x04", "0x05", "0x06", "0x07",
    "0x08", "0x09", "0x0a", "0x0b", "0x0c", "0x0d", "0x0e", "0x0f",
    "0x10", "0x11", "0x12", "0x13", "0x14", "0x15", "0x16", "0x17",
    "0x18", "0x19", "0x1a", "0x1b", "0x1c", "0x1d", "0x1e", "0x1f"
]

# 96-bit nonce (12 bytes)
nonce = [
    "0x00", "0x00", "0x00", "0x09", "0x00", "0x00", "0x00", "0x4a",
    "0x00", "0x00", "0x00", "0x00"
]

# 32-bit counter
counter = "0x01"

# Test plaintext: "Ladies and Gentlemen of the class of '99"
plaintext = [
    "0x4c", "0x61", "0x64", "0x69", "0x65", "0x73", "0x20", "0x61",
    "0x6e", "0x64", "0x20", "0x47", "0x65", "0x6e", "0x74", "0x6c",
    "0x65", "0x6d", "0x65", "0x6e", "0x20", "0x6f", "0x66", "0x20",
    "0x74", "0x68", "0x65", "0x20", "0x63", "0x6c", "0x61", "0x73",
    "0x73", "0x20", "0x6f", "0x66", "0x20", "0x27", "0x39", "0x39"
]

# AES test vectors
[aes]
# 128-bit key (16 bytes)
key_128 = [
    "0x2b", "0x7e", "0x15", "0x16", "0x28", "0xae", "0xd2", "0xa6",
    "0xab", "0xf7", "0x15", "0x88", "0x09", "0xcf", "0x4f", "0x3c"
]

# 192-bit key (24 bytes)
key_192 = [
    "0x8e", "0x73", "0xb0", "0xf7", "0xda", "0x0e", "0x64", "0x52",
    "0xc8", "0x10", "0xf3", "0x2b", "0x80", "0x90", "0x79", "0xe5",
    "0x62", "0xf8", "0xea", "0xd2", "0x52", "0x2c", "0x6b", "0x7b"
]

# 256-bit key (32 bytes)
key_256 = [
    "0x60", "0x3d", "0xeb", "0x10", "0x15", "0xca", "0x71", "0xbe",
    "0x2b", "0x73", "0xae", "0xf0", "0x85", "0x7d", "0x77", "0x81",
    "0x1f", "0x35", "0x2c", "0x07", "0x3b", "0x61", "0x08", "0xd7",
    "0x2d", "0x98", "0x10", "0xa3", "0x09", "0x14", "0xdf", "0xf4"
]

# Test plaintext block (16 bytes)
plaintext_block = [
    "0x6b", "0xc1", "0xbe", "0xe2", "0x2e", "0x40", "0x9f", "0x96",
    "0xe9", "0x3d", "0x7e", "0x11", "0x73", "0x93", "0x17", "0x2a"
]

# IV for CTR mode (16 bytes)
iv = [
    "0xf0", "0xf1", "0xf2", "0xf3", "0xf4", "0xf5", "0xf6", "0xf7",
    "0xf8", "0xf9", "0xfa", "0xfb", "0xfc", "0xfd", "0xfe", "0xff"
]

# Number of rounds
rounds_128 = "10"
rounds_192 = "12"
rounds_256 = "14"

# Test configuration
[test]
# Enable comprehensive testing
run_all_tests = true

# Performance testing
benchmark_mode = false

# Verification mode
verify_proofs = true

# Debug output
debug_output = false